FROM node:22-alpine AS builder
COPY package.json package-lock.json* /
RUN cd / && npm install
WORKDIR /frontend
COPY . .
RUN node /node_modules/.bin/vite build

FROM alpine:latest
COPY --from=builder /frontend/dist /frontend-dist
CMD ["sh", "-c", "cp -r /frontend-dist/. /frontend/"]
