
services:
  corsproxy:
    build:
      context: ./corsproxy
      dockerfile: Dockerfile.prod
    restart: unless-stopped
    ports:
      - "8000:8000"
    environment:
      FLASK_ENV: production
#    depends_on:
#      - redis
    healthcheck:
      test: ["CMD-SHELL", "curl -f http://localhost|| exit 1"]
      interval: 30s
      timeout: 10s
      retries: 3
    env_file: rproxy_config.env
  nginx:
    build:
      context: ./nginx
      dockerfile: Dockerfile.prod
    ports:
      - "443:443"
      - "80:80"
    restart: unless-stopped
    depends_on:
      - corsproxy
    volumes:
      - /etc/letsencrypt:/etc/letsencrypt:ro
      - silence:/var/www/silence:ro
    environment:
      - FLASK_ENV=production
  silence:
    build:
      context: ./silence
      dockerfile: Dockerfile.prod
    volumes:
      - silence:/silence

volumes:
  silence:

networks:
  app-network:
    driver: bridge
