services:
  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile.dev
    ports:
      - "5000:5000"
    environment:
      DEBUG: "true"
      LOGGER_LEVEL: "DEBUG"
      VITE_DEV_SERVER: "true"
    env_file:
      - path: ./backend_secrets.env
        required: true
    healthcheck:
      test: ["CMD-SHELL", "curl -f http://localhost:5000 || exit 1"]
      interval: 30s
      timeout: 10s
      retries: 3
    volumes:
      - ./backend:/backend
      - ./frontend/dist:/backend/static

  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile.dev
    ports:
      - "5173:5173"
    volumes:
      - ./frontend:/frontend
