services:
  corsproxy:
    build:
      context: ./corsproxy
      dockerfile: Dockerfile.dev
    depends_on:
      silence:
        condition: service_completed_successfully
    ports:
      - "5000:5000"
    environment:
      FLASK_ENV: production
      DEBUG: "true"
    env_file:
      - path: ./corsproxy_secrets.env
        required: true
#      HTTP_SERVER_PORT: 80
#    depends_on:
#      - redis
    healthcheck:
      test: ["CMD-SHELL", "curl -f http://localhost:5000 || exit 1"]
      interval: 30s
      timeout: 10s
      retries: 3
    volumes:
      - ./corsproxy:/corsproxy
      - ./silence:/corsproxy/static
  silence:
    build:
      context: ./silence
      dockerfile: Dockerfile.dev
    volumes:
      - ./silence:/silence


networks:
  app-network:
    driver: bridge
