FROM python:3.14
WORKDIR /app
COPY requirements.txt .
RUN pip install -r requirements.txt
COPY . .
#CMD ["python", "app.py"]


# Expose the application port
#EXPOSE 5000

# Run the application
#CMD ["gunicorn", "-w", "4", "-b", "0.0.0.0:5000", "app:app"]

CMD ["flask", "run", "--host=0.0.0.0", "--reload"]
