


    upstream app_server {
        server corsproxy:8000;
    }

    server {
        listen 80;
        listen 443 ssl;
        server_name tezcat.fr;

        ssl_certificate /etc/letsencrypt/live/tezcat.fr/fullchain.pem;
        ssl_certificate_key /etc/letsencrypt/live/tezcat.fr/privkey.pem;

	location /silence {
		root /var/www/;
	}

        location / {
        proxy_pass http://corsproxy:8000;
        }
}
